FROM jenkins/jenkins:lts
USER root
# Instalamos el cliente de Docker para que Jenkins pueda ejecutar "docker build"
RUN apt-get update && apt-get install -y docker.io
# Volvemos al usuario jenkins por seguridad
USER jenkins