services:
  gateway:
    container_name: securenet-gateway
    image: 812752207341.dkr.ecr.eu-west-3.amazonaws.com/securenet-gateway:latest
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #   - ./docker/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    #   - ./docker/gateway/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
    networks:
      - dmz
    labels:
      com.newrelic.monitor: "true"
      com.newrelic.app: "securenet"
      com.newrelic.service: "gateway"
    restart: unless-stopped

  frontend:
    container_name: securenet-frontend
    image: 812752207341.dkr.ecr.eu-west-3.amazonaws.com/securenet-frontend:latest
    networks:
      - dmz
    labels:
      com.newrelic.monitor: "true"
      com.newrelic.app: "securenet"
      com.newrelic.service: "frontend"
    restart: unless-stopped

  api:
    container_name: securenet-api
    image: 812752207341.dkr.ecr.eu-west-3.amazonaws.com/securenet-api:latest
    environment:
      - PORT=3001
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_ACCOUNT_ID=${NEW_RELIC_ACCOUNT_ID}
      - NEW_RELIC_API_KEY=${NEW_RELIC_API_KEY}
    networks:
      - dmz
    labels:
      com.newrelic.monitor: "true"
      com.newrelic.app: "securenet"
      com.newrelic.service: "api"
    restart: unless-stopped
    
  newrelic-infra:
    container_name: securenet-newrelic-infra
    image: newrelic/infrastructure:latest
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NRIA_DISPLAY_NAME=securenet-host
      - NRIA_HOST_ROOT=/host
      - NRIA_PASSTHROUGH_ENVIRONMENT=KUBERNETES_SERVICE_HOST,KUBERNETES_SERVICE_PORT
      - NRIA_VERBOSE=0
      # Enable Docker integration
      - NRIA_DOCKER_ENABLED=true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - ./docker/newrelic/docker-config.yml:/etc/newrelic-infra/integrations.d/docker-config.yml:ro
    network_mode: host
    pid: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
    restart: unless-stopped
    labels:
      com.newrelic.monitor: "false"
      
  n8n:
    container_name: securenet-n8n
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    # volumes:
    #   - ./docker/n8n/data:/home/node/.n8n
    networks:
      - dmz
    labels:
      com.newrelic.monitor: "true"
      com.newrelic.app: "securenet"
      com.newrelic.service: "n8n"
    restart: unless-stopped

networks:
  dmz:
    driver: bridge
