services:
  gateway:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/gateway/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/gateway/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - api
      - newrelic-infra
    networks:
      - dmz

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    networks:
      - dmz

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - port=3001
      - NEW_RELIC_LICENSE_KEY= "${NRIC_LICENSE_KEY}"
      - NEW_RELIC_ACCOUNT_ID= "${NRIC_ACCOUNT_ID}"
    networks:
      - dmz
  newrelic-infra:
    image: newrelic/infrastructure:latest
    environment:
      - NRIA_LICENSE_KEY="${NRIC_LICENSE_KEY}"
      - NRIA_DISPLAY_NAME=securenet-host
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    network_mode: host
    pid: "host"
    privileged: true
    cap_add:
      - SYS_PTRACE
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    volumes:
      - ./docker/n8n/data:/home/node/.n8n
    networks:
      - dmz

networks:
  dmz:
    driver: bridge